// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL5_8cdUR3hMX-I5rBXIpACRKtOqtp7DM',
    appId: '1:364047496090:web:01a61260a02cb173478023',
    messagingSenderId: '364047496090',
    projectId: 'markerapp-9a526',
    authDomain: 'markerapp-9a526.firebaseapp.com',
    storageBucket: 'markerapp-9a526.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZRyHKD-FEeA7PWyR9qSXDxIPv1f8ONvU',
    appId: '1:364047496090:android:4ccca34ccaf8770f478023',
    messagingSenderId: '364047496090',
    projectId: 'markerapp-9a526',
    storageBucket: 'markerapp-9a526.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS7hKTpBk1hWvCQajqNGjrPJpt5iOR0A8',
    appId: '1:364047496090:ios:884ae2f97a7c3256478023',
    messagingSenderId: '364047496090',
    projectId: 'markerapp-9a526',
    storageBucket: 'markerapp-9a526.appspot.com',
    iosBundleId: 'com.example.markerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCS7hKTpBk1hWvCQajqNGjrPJpt5iOR0A8',
    appId: '1:364047496090:ios:884ae2f97a7c3256478023',
    messagingSenderId: '364047496090',
    projectId: 'markerapp-9a526',
    storageBucket: 'markerapp-9a526.appspot.com',
    iosBundleId: 'com.example.markerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCL5_8cdUR3hMX-I5rBXIpACRKtOqtp7DM',
    appId: '1:364047496090:web:14d378005d62e49b478023',
    messagingSenderId: '364047496090',
    projectId: 'markerapp-9a526',
    authDomain: 'markerapp-9a526.firebaseapp.com',
    storageBucket: 'markerapp-9a526.appspot.com',
  );
}
